# Ввод и вывод данных (по умолчанию вводятся строковые значения)
print('Введите а')
a = input()
print('Введите b')
b = input()
print(a, ' + ', b, ' = ', a + b)
print('{} {}'.format(a, b))
print(f'{a} {b}')

# Ввод и вывод данных (числовые значения)
print('Введите а')
a = int(input())
print('Введите b')
b = int(input())
print(a, ' + ', b, ' = ', a + b)
print('{} {}'.format(a, b))
print(f'{a} {b}')

# Ввод и вывод данных (значения с плавающей точкой)
print('Введите а')
a = float(input())
print('Введите b')
b = float(input())
print(a, ' + ', b, ' = ', a + b)
print('{} {}'.format(a, b))
print(f'{a} {b}')